mode: sr
gpu_ids: [0]
scale: 4
is_train: true
run_range: 1
save_image: true
img_range: 2047
mask_training: mask_collate_fn

datasets:
    train1: # train datasets
        name: QB-MIX4
        mode: LRHR
        # subset: [0.5, 0.75] # used for Interantvie-Training-Epoch
        img_range: 2047
        dataroot_HR: ../PanSharp_dataset/QB/train/MTF/MIX_4_rand/HRMS_npy
        dataroot_LR: ../PanSharp_dataset/QB/train/MTF/MIX_4_rand/LRMS_npy
        dataroot_PAN: ../PanSharp_dataset/QB/train/MTF/4bands/LRPAN_npy
        data_type: npy
        n_workers: 4
        repeat: 2
        batch_size: 8
        LR_size: 16
        use_flip: true
        use_rot: true
        noise: .
##
# train2: # train datasets
    # name: QB-FIX4
    #     mode: LRHR
    #     # subset: [0.5, 0.75] # used for Interantvie-Training-Epoch
    #     img_range: 2047
    #     dataroot_HR: ../PanSharp_dataset/QB/train/MTF/4bands/HRMS_npy
    #     dataroot_LR: ../PanSharp_dataset/QB/train/MTF/4bands/LRMS_npy
    #     dataroot_PAN: ../PanSharp_dataset/QB/train/MTF/4bands/LRPAN_npy
    #     data_type: npy
    #     n_workers: 4
    #     repeat: 2
    #     batch_size: 8
    #     LR_size: 16
    #     use_flip: true
    #     use_rot: true
    #     noise: .


    val: # validation datasets
        name: NBU_QB
        mode: LRHR
        img_range: 2047
        data_type: npy
        dataroot_HR: ../PanSharp_dataset/QB/value/MTF/MIX_4_rand/HRMS_npy
        dataroot_LR: ../PanSharp_dataset/QB/value/MTF/MIX_4_rand/LRMS_npy
        dataroot_PAN: ../PanSharp_dataset/QB/value/MTF/4bands/LRPAN_npy

## hyper-parameters for network architecture
networks:
    which_model: ArbRPN  # this value must be same with the filename of 'your_network_name'.py
    hid_dim: 64
    input_dim: 64
    num_features: 64
    in_channels: 8
    scale: 4
    num_resblocks: 3
    num_cycle: 5

# the setting for optimizer, loss function, learning_strategy, etc.
solver:
    type: ADAM
    learning_rate: 0.0001
    weight_decay: 0
    lr_scheme: MultiStepLR
    lr_steps: [200, 400, 600, 800]
    lr_gamma: 0.5
    loss_type: myloss
    manual_seed: 0
    num_epochs: 1000
    skip_threshold: 100
    save_ckp_step: 1000
    save_vis_step: 1 # be useful only when save_image is true
    pretrain: null
    pretrained_path: null # path for pre-trained model 

